server:
  port: 8090

spring:
  application:
    name: services

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}